galaxy_info:
  author: Michael Wadman
  description: Manages Kubernetes objects.
  license: "MIT"
  min_ansible_version: "2.9"
  galaxy_tags:
    - "kubernetes"
    - "k8s"
  platforms:
    - name: GenericLinux
      versions:
        - all
dependencies: []
